version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "wapp-pyros2097-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-grb3hle00qk9"
s3_prefix = "wapp-pyros2097-dev"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "DomainName=\"wapp.pyros2097.dev\" HostedZoneId=\"Z0469276792OXT6RNZF5\" AcmCertificateArn=\"arn:aws:acm:us-east-1:719747015987:certificate/16acd03e-b59a-459c-8a3f-5caa50df7079\""
